In [2]:
# Explain the difference between a Python list and a NumPy array in terms of memory usage and performance.Then, write a program that creates both and performs element-wise multiplication.

# Python list
lst = [1, 2, 3, 4]
list_result = [x * 2 for x in lst]
print("List result:", list_result)

# NumPy array
import numpy as np
arr = np.array([1, 2, 3, 4])
array_result = arr * 2
print("Array result:", array_result)

List result: [2, 4, 6, 8]
Array result: [2 4 6 8]


In [3]:
# What is broadcasting in NumPy?Create a 3×3 NumPy array and add a 1D array to it using broadcasting. Explain how NumPy applies the operation internally.

import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([10,20,30])
result = A + b
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
# What are missing values in Pandas and how are they represented? Create a DataFrame with missing values and write code to:
#• Detect missing values
#• Replace them with the column mean
#Explain each step.

import pandas as pd
import numpy as np
df = pd.DataFrame({
    "A": [1, 2, np.nan, 4],
    "B": [5, np.nan, 7, 8]
})
print("Missing values:\n", df.isna())

# replace with mean
df_filled = df.fillna(df.mean())

print("\nFilled DataFrame:\n", df_filled)


Original DataFrame:


In [7]:
 #Explain boolean indexing in NumPy or Pandas. Create a DataFrame with at least 5 columns and filter rows based on two conditions using logical operators. Explain how filtering works internally.

import pandas as pd

df = pd.DataFrame({
    "name": ["A","B","C","D","E"],
    "age": [22, 35, 28, 40, 30],
    "salary": [20000, 50000, 30000, 80000, 45000],
    "dept": ["IT","HR","IT","Finance","IT"],
    "rating": [3,5,4,5,2]
})

filtered = df[(df["age"] > 25) & (df["salary"] > 30000)]
print(filtered)


  name  age  salary     dept  rating
1    B   35   50000       HR       5
3    D   40   80000  Finance       5
4    E   30   45000       IT       2


In [8]:
#. What is the purpose of the groupby() function in Pandas? Create a DataFrame with categorical data (e.g., department & salary) and calculate the average salary per department using groupby(). Explain the output.

import pandas as pd

df = pd.DataFrame({
    "dept": ["IT","IT","HR","HR","Finance"],
    "salary": [40000,60000,30000,35000,80000]
})

avg_salary = df.groupby("dept")["salary"].mean()

print(avg_salary)


dept
Finance    80000.0
HR         32500.0
IT         50000.0
Name: salary, dtype: float64
